language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t g1git/g1-react -f Dockerfile.dev .

script:
 - docker run -e CI=true g1git/g1-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "g1-react"
 env: "G1react-env"
 bucket-name: "elasticbeanstalk-us-east-2-326198890687"
 bucket-path: "g1-react"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secure_access_key: 
  secure: "$AWS_SECURE_KEY"

