language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t g1git/g1-react -f Dockerfile.dev .

script:
 - docker run -e CI=true g1git/g1-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "g1-react"
 env: "G1react-env"
 bucket-name: "elasticbeanstalk-us-east-2-326198890687"
 bucket-path: "g1-react"
 on:
  branch: master
 secure_key_id: AKIAUX4XYCC77XY5G7OM
 access_access_key: "ZrCCBLn+G/pxX0v4R2YV9WxUg4CRd0f+qFCfR0xi"

